package sistemausuario;

import javax.swing.JOptionPane;
import java.sql.SQLException;
import javax.swing.*;
import java.awt.*;
import java.sql.SQLException;
import java.util.List;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author fabio
 */
public class AlterarUsuario extends javax.swing.JFrame {

    /**
     * Creates new form AlterarUsuario
     */
    public AlterarUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Verificar = new javax.swing.JButton();
        Atualizar = new javax.swing.JButton();
        Excluir = new javax.swing.JButton();
        loginText = new javax.swing.JTextField();
        idText = new javax.swing.JTextField();
        senhaTxt = new javax.swing.JTextField();
        Sair = new javax.swing.JButton();
        Id = new javax.swing.JLabel();
        Login = new javax.swing.JLabel();
        Senha = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Verificar.setText("Verificar");
        Verificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerificarActionPerformed(evt);
            }
        });
        getContentPane().add(Verificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        Atualizar.setText("Atualizar");
        Atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtualizarActionPerformed(evt);
            }
        });
        getContentPane().add(Atualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, -1, -1));

        Excluir.setText("Excluir");
        Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(Excluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, -1, -1));

        loginText.setBackground(new java.awt.Color(126, 190, 252));
        loginText.setForeground(new java.awt.Color(0, 0, 0));
        loginText.setCaretColor(new java.awt.Color(0, 0, 0));
        loginText.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        getContentPane().add(loginText, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 270, -1));

        idText.setBackground(new java.awt.Color(126, 190, 252));
        idText.setCaretColor(new java.awt.Color(0, 0, 0));
        idText.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        idText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTextActionPerformed(evt);
            }
        });
        getContentPane().add(idText, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 70, -1));

        senhaTxt.setBackground(new java.awt.Color(126, 190, 252));
        senhaTxt.setForeground(new java.awt.Color(0, 0, 0));
        senhaTxt.setCaretColor(new java.awt.Color(0, 0, 0));
        senhaTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        getContentPane().add(senhaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 270, -1));

        Sair.setText("Sair");
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });
        getContentPane().add(Sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, -1));

        Id.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        Id.setForeground(new java.awt.Color(0, 0, 0));
        Id.setText("Id");
        getContentPane().add(Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 20, -1));

        Login.setForeground(new java.awt.Color(0, 0, 0));
        Login.setText("Login");
        getContentPane().add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        Senha.setForeground(new java.awt.Color(0, 0, 0));
        Senha.setText("Senha");
        getContentPane().add(Senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabio\\OneDrive\\Documentos\\NetBeansProjects\\SistemaUsuario\\build\\classes\\sistemausuario\\Fundo1.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 320));

        setSize(new java.awt.Dimension(427, 320));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void VerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerificarActionPerformed
                                           
    try {
    DAO dao = new DAO();
    List<Usuario> usuarios = dao.obterTodosUsuarios();

    if (!usuarios.isEmpty()) {
        String[] columnNames = {"ID", "Nome", "Senha"};
        Object[][] data = new Object[usuarios.size()][3];

        for (int i = 0; i < usuarios.size(); i++) {
            Usuario usuario = usuarios.get(i);
            data[i][0] = usuario.getId();
            data[i][1] = usuario.getNome();
            data[i][2] = usuario.getSenha();
        }

        JTable table = new JTable(data, columnNames);
        table.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        table.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                int selectedRow = table.getSelectedRow();

                if (selectedRow != -1) {
                    int id = (int) table.getValueAt(selectedRow, 0);
                    String nome = (String) table.getValueAt(selectedRow, 1);
                    String senha = (String) table.getValueAt(selectedRow, 2);

                    // Atualizar os campos com as informações do usuário selecionado
                    idText.setText(String.valueOf(id));
                    loginText.setText(nome);
                    senhaTxt.setText(senha);
                }
            }
        });

        JScrollPane scrollPane = new JScrollPane(table);
        scrollPane.setPreferredSize(new Dimension(400, 300));

        JOptionPane.showMessageDialog(null, scrollPane, "Usuários", JOptionPane.INFORMATION_MESSAGE);
    } else {
        JOptionPane.showMessageDialog(null, "Não há usuários cadastrados.");
    }
} catch (SQLException e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(null, "Erro ao executar consulta SQL: " + e.getMessage());
}
   
    }//GEN-LAST:event_VerificarActionPerformed

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        // TODO add your handling code here:

        TelaInicio TelaInicio = new TelaInicio();
        TelaInicio.setVisible(true);

        dispose();

    }//GEN-LAST:event_SairActionPerformed

    private void idTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTextActionPerformed

    private void AtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtualizarActionPerformed
    int id = Integer.parseInt(idText.getText()); // Obtém o ID do usuário a ser atualizado
    String novoNome = loginText.getText(); // Obtém o novo nome digitado
    String novaSenha = senhaTxt.getText(); // Obtém a nova senha digitada
    
    Usuario usuario = new Usuario(id, novoNome, novaSenha);
    
    DAO dao = new DAO();
    try {
        dao.atualizarUsuario(usuario); // Chama o método de atualização no DAO passando o objeto Usuario
        JOptionPane.showMessageDialog(null, "Usuário atualizado com sucesso.");
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Erro ao atualizar usuário: " + e.getMessage());
    }                                      
     
    }//GEN-LAST:event_AtualizarActionPerformed

    private void ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirActionPerformed
        
    int confirm = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir o usuário?", "Confirmação de exclusão", JOptionPane.YES_NO_OPTION);
    
    if (confirm == JOptionPane.YES_OPTION) {
        // Obtenha o ID do usuário que você deseja excluir
        int idUsuario = Integer.parseInt(idText.getText()); 
        
        // Chame o método de exclusão no seu objeto DAO
        DAO dao = new DAO();
        try {
            dao.excluirUsuario(idUsuario);
            // Realize qualquer ação adicional após a exclusão, se necessário

            // Exemplo: exiba uma mensagem de sucesso
            JOptionPane.showMessageDialog(null, "Usuário excluído com sucesso");
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro ao excluir usuário: " + e.getMessage());
        }
    }

    }//GEN-LAST:event_ExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlterarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlterarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlterarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlterarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlterarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atualizar;
    private javax.swing.JButton Excluir;
    private javax.swing.JLabel Id;
    private javax.swing.JLabel Login;
    private javax.swing.JButton Sair;
    private javax.swing.JLabel Senha;
    private javax.swing.JButton Verificar;
    private javax.swing.JTextField idText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField loginText;
    private javax.swing.JTextField senhaTxt;
    // End of variables declaration//GEN-END:variables
}
