package sistemausuario;


import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.ResultSet;
import javax.swing.JOptionPane;




/**
 *
 * @author fabio
 */
public class Cadastro extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        loginTxt = new javax.swing.JTextPane();
        SenhaTxt = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Senha");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        jLabel5.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Login");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        jButton3.setText("VOLTAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, -1, -1));
        jButton3.getAccessibleContext().setAccessibleName("voltar");

        loginTxt.setBackground(new java.awt.Color(26, 29, 94));
        loginTxt.setForeground(new java.awt.Color(255, 255, 255));
        loginTxt.setCaretColor(new java.awt.Color(255, 255, 255));
        loginTxt.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        loginTxt.setSelectedTextColor(new java.awt.Color(225, 225, 225));
        loginTxt.setSelectionColor(new java.awt.Color(225, 225, 225));
        jScrollPane1.setViewportView(loginTxt);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 210, -1));

        SenhaTxt.setBackground(new java.awt.Color(26, 29, 94));
        SenhaTxt.setForeground(new java.awt.Color(255, 255, 255));
        SenhaTxt.setToolTipText("");
        SenhaTxt.setCaretColor(new java.awt.Color(255, 255, 255));
        SenhaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SenhaTxtActionPerformed(evt);
            }
        });
        getContentPane().add(SenhaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 210, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabio\\OneDrive\\Documentos\\NetBeansProjects\\SistemaUsuario\\src\\sistemausuario\\Azul.jpg")); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 320));

        setSize(new java.awt.Dimension(427, 320));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String usuario = loginTxt.getText();
String senha = SenhaTxt.getText();

// Remover espaços em branco no início e no final do nome de usuário
usuario = usuario.trim();

// Verifica se o nome de usuário está em branco
if (usuario.isEmpty()) {
    JOptionPane.showMessageDialog(null, "Por favor, informe um nome de usuário válido.");
    return;
}

Usuario usuarioNovo = new Usuario(usuario, senha);

int idUsuario = 0; // Declare a variável fora do bloco try

try {
    Connection connection = ConexaoDB.obtemConexao();
    
    // Verifica se já existe um usuário com o mesmo nome
    String selectQuery = "SELECT COUNT(*) AS count FROM usuario WHERE nome = ?";
    PreparedStatement selectStatement = connection.prepareStatement(selectQuery);
    selectStatement.setString(1, usuarioNovo.getNome());
    ResultSet resultSet = selectStatement.executeQuery();
    resultSet.next();
    int count = resultSet.getInt("count");
    if (count > 0) {
        throw new SQLException("Usuário já existe.");
    }

    String insertQuery = "INSERT INTO usuario (nome, senha) VALUES (?, ?)";

    PreparedStatement statement = connection.prepareStatement(insertQuery, new String[]{"id"});
    statement.setString(1, usuarioNovo.getNome());
    statement.setString(2, usuarioNovo.getSenha());
    statement.executeUpdate();

    ResultSet generatedKeys = statement.getGeneratedKeys();
    if (generatedKeys.next()) {
        idUsuario = generatedKeys.getInt(1); // Atribua o valor do ID gerado à variável idUsuario
        System.out.println("ID de usuário gerado automaticamente: " + idUsuario);
    }

    statement.close();
    connection.close();

    // Restante do código para a inserção de gastos ou tipos, usando o idUsuario como referência

    // Exibe uma mensagem de sucesso
    JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso!");

} catch (SQLException ex) {
    ex.printStackTrace();
}

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        LoginTela TelaDeLogin = new LoginTela();
        TelaDeLogin.setVisible(true);
        
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void SenhaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SenhaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SenhaTxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
     
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField SenhaTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane loginTxt;
    // End of variables declaration//GEN-END:variables
}
