/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistemausuario;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.*;
import java.sql.Statement;
import javax.swing.JOptionPane;


/**
 *
 * @author fabio
 */
public class TelaInicio extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicio
     */
    public TelaInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        X = new javax.swing.JButton();
        addGasto = new javax.swing.JButton();
        addTipos = new javax.swing.JButton();
        AlterarUsuario = new javax.swing.JButton();
        verificarBotão = new javax.swing.JButton();
        Fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        X.setText("X");
        X.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XActionPerformed(evt);
            }
        });
        getContentPane().add(X, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 10, -1, -1));

        addGasto.setText("Adicionar Gastos");
        addGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addGastoActionPerformed(evt);
            }
        });
        getContentPane().add(addGasto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 130, 70));

        addTipos.setText("Adicionar Tipos");
        addTipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTiposActionPerformed(evt);
            }
        });
        getContentPane().add(addTipos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 130, 70));

        AlterarUsuario.setText("Alterar usuario");
        AlterarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlterarUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(AlterarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 130, 70));

        verificarBotão.setText("Verificar Gastos");
        verificarBotão.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verificarBotãoActionPerformed(evt);
            }
        });
        getContentPane().add(verificarBotão, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, 430, 100));

        Fundo.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabio\\OneDrive\\Documentos\\NetBeansProjects\\SistemaUsuario\\build\\classes\\sistemausuario\\fundoTelaInico.png")); // NOI18N
        Fundo.setInheritsPopupMenu(false);
        getContentPane().add(Fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, -1));

        setSize(new java.awt.Dimension(1198, 480));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void XActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_XActionPerformed

    private void addTiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTiposActionPerformed
        // TODO add your handling code here:
        AddTipo AddTipo = new AddTipo();
        AddTipo.setVisible(true);
        
        dispose();
    }//GEN-LAST:event_addTiposActionPerformed

    private void addGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addGastoActionPerformed
        // TODO add your handling code here:
        AddGasto AddGasto = new AddGasto();
        AddGasto.setVisible(true);
        
        dispose();
    }//GEN-LAST:event_addGastoActionPerformed

    private void AlterarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterarUsuarioActionPerformed
        // TODO add your handling code here:
        AlterarUsuario AlterarUsuario = new AlterarUsuario();
        AlterarUsuario.setVisible(true);
        
        dispose();
    }//GEN-LAST:event_AlterarUsuarioActionPerformed

    private void verificarBotãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verificarBotãoActionPerformed
   // Obter os dados do banco de dados e exibi-los em um JOptionPane
String url = "jdbc:mysql://localhost/A3?serverTimezone=UTC";
String user = "root";
String password = "2503";
String tabela = "TB_GASTOS";

try (Connection connection = DriverManager.getConnection(url, user, password)) {
    Statement statement = connection.createStatement();
    String sql = "SELECT * FROM " + tabela;
    ResultSet resultSet = statement.executeQuery(sql);

    StringBuilder gastos = new StringBuilder();
    while (resultSet.next()) {
        int codigo = resultSet.getInt("CODIGO_G");
        String nome = resultSet.getString("NOME");
        double valor = resultSet.getDouble("VALOR");
        int tipo = resultSet.getInt("TIPO");
        java.util.Date data = resultSet.getDate("DATA");

        gastos.append("Código: ").append(codigo).append(", Nome: ").append(nome)
            .append(", Valor: ").append(valor).append(", Tipo: ").append(tipo)
            .append(", Data: ").append(data).append("\n");
    }

    JOptionPane.showMessageDialog(this, gastos.toString(), "Gastos", JOptionPane.INFORMATION_MESSAGE);

    resultSet.close();
    statement.close();
} catch (SQLException e) {
    e.printStackTrace();
}


    }//GEN-LAST:event_verificarBotãoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AlterarUsuario;
    private javax.swing.JLabel Fundo;
    private javax.swing.JButton X;
    private javax.swing.JButton addGasto;
    private javax.swing.JButton addTipos;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton verificarBotão;
    // End of variables declaration//GEN-END:variables
}
